# File Tracking - CSV with Pandas

This notebook demonstrates FlowBook's file tracking with pandas CSV operations.
Both `pd.read_csv()` and `df.to_csv()` are tracked.

In [1]:
import pandas as pd
import numpy as np

✓ Run: 1 ms | State: 2 ms | Check: 2 ms

## Create and save a DataFrame to CSV

The file write will appear in the `writes` list as `file:sales_data.csv`.

In [2]:
# Create sample sales data
df = pd.DataFrame({
    'product': ['Widget A', 'Widget B', 'Widget C', 'Widget D'],
    'price': [10.99, 24.99, 5.99, 49.99],
    'quantity': [100, 50, 200, 25]
})

# Save to CSV
df.to_csv('sales_data.csv', index=False)
print('Saved sales_data.csv')
df

Saved sales_data.csv

    product  price  quantity
0  Widget A  10.99       100
1  Widget B  24.99        50
2  Widget C   5.99       200
3  Widget D  49.99        25

✓ Run: 26 ms | State: 5 ms | Check: 2 ms | Writes: df,file:sales_data.csv

## Read the CSV file

The file read will appear in the `reads` list as `file:sales_data.csv`.

In [3]:
# Read the CSV back
loaded_df = pd.read_csv('sales_data.csv')
loaded_df

    product  price  quantity
0  Widget A  10.99       100
1  Widget B  24.99        50
2  Widget C   5.99       200
3  Widget D  49.99        25

✓ Run: 10 ms | State: 7 ms | Check: 3 ms | Reads: file:sales_data.csv | Writes: loaded_df

## Process and analyze the data

In [4]:
# Calculate total revenue
loaded_df['revenue'] = loaded_df['price'] * loaded_df['quantity']
total_revenue = loaded_df['revenue'].sum()
print(f'Total revenue: ${total_revenue:.2f}')
loaded_df

Total revenue: $4796.25

    product  price  quantity  revenue
0  Widget A  10.99       100  1099.00
1  Widget B  24.99        50  1249.50
2  Widget C   5.99       200  1198.00
3  Widget D  49.99        25  1249.75

✓ Run: 9 ms | State: 16 ms | Check: 11 ms | Reads: loaded_df | Writes: total_revenue,_4[revenue]

## Update the source file

If we modify the CSV file, cells that read it become stale.

In [5]:
# Add a new product and save
new_product = pd.DataFrame({
    'product': ['Widget E'],
    'price': [99.99],
    'quantity': [10]
})
updated_df = pd.concat([df, new_product], ignore_index=True)
updated_df.to_csv('sales_data.csv', index=False)
print('Updated sales_data.csv with new product')

Updated sales_data.csv with new product

✓ Run: 3 ms | State: 28 ms | Check: 6 ms | Reads: df | Writes: updated_df,new_product,file:sales_data.csv

## Save processed results to a different file

In [6]:
# Save the processed data with revenue to a new file
loaded_df.to_csv('sales_with_revenue.csv', index=False)
print('Saved sales_with_revenue.csv')

Saved sales_with_revenue.csv

✓ Run: 2 ms | State: 56 ms | Check: 6 ms | Reads: loaded_df | Writes: file:sales_with_revenue.csv

## Cleanup

In [7]:
import os
for f in ['sales_data.csv', 'sales_with_revenue.csv']:
    if os.path.exists(f):
        os.remove(f)
        print(f'Cleaned up {f}')

Cleaned up sales_data.csv
Cleaned up sales_with_revenue.csv

✓ Run: 2 ms | State: 82 ms | Check: 6 ms | Writes: f